package service

import (
	"errors"
	"fmt"
	"html"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type Launchd struct {
	Home   string
	LogDir string
	UID    int
	Run    Runner
}

func (l *Launchd) Name() string { return "launchd" }
func (l *Launchd) Path() string {
	return filepath.Join(l.Home, "Library", "LaunchAgents", Label+".plist")
}
func (l *Launchd) domain() string  { return fmt.Sprintf("gui/%d", l.UID) }
func (l *Launchd) service() string { return l.domain() + "/" + Label }

func (l *Launchd) Render(o InstallOptions) string {
	x := html.EscapeString
	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by agentsd service install. Re-run it rather than editing. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>` + Label + `</string>
  <key>ProgramArguments</key>
  <array>
`)
	var argv []string
	if o.EnvFile != "" {
		// launchd has no EnvironmentFile; source it at start so secrets are
		// never copied into the plist.
		argv = []string{"/bin/sh", "-c", `set -a; . "$1"; set +a; exec "$0" daemon`, o.Binary, o.EnvFile}
	} else {
		argv = []string{o.Binary, "daemon"}
	}
	for _, a := range argv {
		b.WriteString("    <string>" + x(a) + "</string>\n")
	}
	b.WriteString(`  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ProcessType</key>
  <string>Background</string>
  <key>ExitTimeOut</key>
  <integer>` + strconv.Itoa(int(StopTimeout.Seconds())) + `</integer>
  <key>StandardOutPath</key>
  <string>` + x(filepath.Join(l.LogDir, "launchd.log")) + `</string>
  <key>StandardErrorPath</key>
  <string>` + x(filepath.Join(l.LogDir, "launchd.log")) + `</string>
`)
	if len(o.Env) > 0 {
		b.WriteString("  <key>EnvironmentVariables</key>\n  <dict>\n")
		for _, k := range sortedKeys(o.Env) {
			b.WriteString("    <key>" + x(k) + "</key>\n    <string>" + x(o.Env[k]) + "</string>\n")
		}
		b.WriteString("  </dict>\n")
	}
	b.WriteString("</dict>\n</plist>\n")
	return b.String()
}

func (l *Launchd) Install(o InstallOptions) error {
	if err := os.MkdirAll(l.LogDir, 0o700); err != nil {
		return err
	}
	if st := l.Status(); st.Loaded {
		_, _ = l.Run("launchctl", "bootout", l.service())
	}
	if err := writeFile(l.Path(), l.Render(o), 0o600); err != nil {
		return err
	}
	_, err := l.Run("launchctl", "bootstrap", l.domain(), l.Path())
	return err
}

func (l *Launchd) Uninstall() error {
	if l.Status().Loaded {
		if _, err := l.Run("launchctl", "bootout", l.service()); err != nil {
			return err
		}
	}
	if err := os.Remove(l.Path()); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	return nil
}

func (l *Launchd) ensureLoaded() error {
	if !l.Status().Loaded {
		if _, err := os.Stat(l.Path()); err != nil {
			return fmt.Errorf("service is not installed (run `agentsd service install`)")
		}
		_, err := l.Run("launchctl", "bootstrap", l.domain(), l.Path())
		return err
	}
	return nil
}

func (l *Launchd) Start() error {
	if err := l.ensureLoaded(); err != nil {
		return err
	}
	_, err := l.Run("launchctl", "kickstart", l.service())
	return err
}

func (l *Launchd) Stop() error {
	if !l.Status().Running {
		return nil
	}
	_, err := l.Run("launchctl", "kill", "SIGTERM", l.service())
	return err
}

func (l *Launchd) Restart() error {
	if err := l.ensureLoaded(); err != nil {
		return err
	}
	_, err := l.Run("launchctl", "kickstart", "-k", l.service())
	return err
}

var (
	pidRE   = regexp.MustCompile(`(?m)^\s*pid = (\d+)`)
	stateRE = regexp.MustCompile(`(?m)^\s*state = (\S+)`)
	pathRE  = regexp.MustCompile(`(?m)^\s*path = (.+)$`)
)

func (l *Launchd) Status() Status {
	st := Status{Manager: l.Name(), Path: l.Path()}
	if _, err := os.Stat(l.Path()); err == nil {
		st.Installed = true
	}
	out, err := l.Run("launchctl", "print", l.service())
	if err != nil {
		st.Detail = "not loaded"
		return st
	}
	// Only a job loaded from our plist is ours to control.
	if m := pathRE.FindStringSubmatch(out); m != nil && strings.TrimSpace(m[1]) != l.Path() {
		st.Detail = "label loaded from a different plist: " + strings.TrimSpace(m[1])
		return st
	}
	st.Loaded = true
	if m := stateRE.FindStringSubmatch(out); m != nil {
		st.Detail = m[1]
		st.Running = m[1] == "running"
	}
	if m := pidRE.FindStringSubmatch(out); m != nil {
		st.PID, _ = strconv.Atoi(m[1])
	}
	return st
}
