package service

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
)

type Systemd struct {
	Dir string // $XDG_CONFIG_HOME/systemd/user
	Run Runner
}

func (s *Systemd) Name() string { return "systemd --user" }
func (s *Systemd) Path() string { return filepath.Join(s.Dir, UnitName) }

// quote escapes a value for an Environment= line.
func quote(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "%", "%%").Replace(s) + `"`
}

func (s *Systemd) Render(o InstallOptions) string {
	var b strings.Builder
	b.WriteString(`# Generated by agentsd service install. Re-run it rather than editing.
[Unit]
Description=agentsd agent supervisor
Documentation=https://github.com/Hunt4Bugs/agentsd

[Service]
Type=simple
ExecStart=` + systemdExecQuote(o.Binary) + ` daemon
Restart=on-failure
RestartSec=2
# The daemon stops its runs itself; only signal the main process first.
KillMode=mixed
TimeoutStopSec=` + strconv.Itoa(int(StopTimeout.Seconds())) + `
`)
	for _, k := range sortedKeys(o.Env) {
		b.WriteString("Environment=" + quote(k+"="+o.Env[k]) + "\n")
	}
	if o.EnvFile != "" {
		b.WriteString("EnvironmentFile=" + o.EnvFile + "\n")
	}
	b.WriteString(`
[Install]
WantedBy=default.target
`)
	return b.String()
}

func systemdExecQuote(p string) string {
	if strings.ContainsAny(p, " \t\"'\\") {
		return quote(p)
	}
	return p
}

func (s *Systemd) ctl(args ...string) (string, error) {
	return s.Run("systemctl", append([]string{"--user"}, args...)...)
}

func (s *Systemd) Install(o InstallOptions) error {
	if err := writeFile(s.Path(), s.Render(o), 0o644); err != nil {
		return err
	}
	if _, err := s.ctl("daemon-reload"); err != nil {
		return err
	}
	_, err := s.ctl("enable", "--now", UnitName)
	return err
}

func (s *Systemd) Uninstall() error {
	if _, err := os.Stat(s.Path()); err == nil {
		_, _ = s.ctl("disable", "--now", UnitName)
	}
	if err := os.Remove(s.Path()); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	_, _ = s.ctl("daemon-reload")
	return nil
}

func (s *Systemd) Start() error   { _, err := s.ctl("start", UnitName); return err }
func (s *Systemd) Stop() error    { _, err := s.ctl("stop", UnitName); return err }
func (s *Systemd) Restart() error { _, err := s.ctl("restart", UnitName); return err }

func (s *Systemd) Status() Status {
	st := Status{Manager: s.Name(), Path: s.Path()}
	if _, err := os.Stat(s.Path()); err == nil {
		st.Installed = true
	}
	out, err := s.ctl("show", UnitName, "-p", "LoadState", "-p", "ActiveState", "-p", "MainPID", "-p", "FragmentPath")
	if err != nil {
		st.Detail = err.Error()
		return st
	}
	props := map[string]string{}
	for _, line := range strings.Split(out, "\n") {
		if k, v, ok := strings.Cut(line, "="); ok {
			props[k] = v
		}
	}
	if fp := props["FragmentPath"]; fp != "" && fp != s.Path() {
		st.Detail = "unit loaded from a different file: " + fp
		return st
	}
	st.Loaded = props["LoadState"] == "loaded"
	st.Running = props["ActiveState"] == "active"
	st.Detail = props["ActiveState"]
	st.PID, _ = strconv.Atoi(props["MainPID"])
	return st
}

// LingerEnabled reports whether systemd keeps this user's services running
// after logout.
func LingerEnabled() (bool, string) {
	u, err := user.Current()
	if err != nil {
		return false, ""
	}
	_, err = os.Stat(filepath.Join("/var/lib/systemd/linger", u.Username))
	return err == nil, fmt.Sprintf("loginctl enable-linger %s", u.Username)
}
